### ISSUE TITLE
Fix IDs to conform to route

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#15]
@SBRitter Missed that this was not fixed in your pull request, see https://github.com/hbz/lobid-organisations/pull/14#issuecomment-62557587

**Comment by acka47** [comment]
Is this still open? I don't really understand this issue. /cc @SBRitter

**Comment by SBRitter** [comment]
If I remember correctly, the problem here was that while the URLs of the web app contained "organisations" in plural, the URL in id of the JSON document had "organisation" in singular. This is fixed I think. See http://beta.lobid.org/organisations/DE-9, you will find: "id":"http://beta.lobid.org/organisations/DE-9".
