### ISSUE TITLE
No Geo coordinates  at all for DE-294

### ISSUE THREAD

**Issue by peterreimer** [hbz/lobid-organisations#154]
No map data for Ruhr-Universität Bochum

**Comment by peterreimer** [comment]
There are even two sets of Geocoordinates: http://lobid.org/organisation?id=DE-294#2011895681-jld
"@graph" : [ {
    "@id" : "_:t1",
    "lat" : [ "51.44510", "51.4451024" ],
    "long" : [ "7.2605524", "7.26055" ]
  },

**Comment by fsteeg** [comment]
Thanks for the report Peter!

I think the issue are these multiple coordinates, see:

http://lobid.org/organisation?id=DE-294&format=full

Displays no map:

http://lobid.org/organisation/DE-294

While a single location like:

http://lobid.org/organisation?id=DE-605&format=full

Is displayed on the map:

http://lobid.org/organisation?id=DE-605

Organisations 2.0 has the correct single location:

http://beta.lobid.org/organisations/DE-294

**Comment by peterreimer** [comment]
Hi Fabian,
i use your API to build a map with all 'Verbundbibliotheken' for the upcoming new hbz website: http://w3.hbz-nrw.de/produkte/verbunddienstleistungen/verbundbibliotheken (currently only accessible from inside the hbz) Do you suggest to switch to Version 2.0 of your API? It is still in beta as far as i understand. Or is it better to modify my code so that it can deal with both single strings or lists of strings for the geocoordinates?

**Comment by fsteeg** [comment]
Oh I see, since it sounded like a UI issue I assumed you didn't need it on the API level.

The beta 2.0 API is quite stable, I don't think we will do major changes to the structure (one exception with an upcoming change is `alternateName`, see https://github.com/hbz/lobid-organisations/issues/107#issuecomment-187064777). We're also careful about it running reliably, since it's used productively in NWBib. It should also provide more and better data compared to the 1.x API, which we are fading out. So, yes, even though it's still beta, I'd recommend using it.

**Comment by peterreimer** [comment]
OK. I will give it a try. 
http://beta.lobid.org/organisations is all currently available documentation?

**Comment by fsteeg** [comment]
Yes.

Here are some details on the supported query string syntax: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-syntax

Let me know if you have any questions.

**Comment by acka47** [comment]
> http://beta.lobid.org/organisations is all currently available documentation?

I also held a bibcast in lobid-organisations 2.0 with several example use cases, see the slides at http://hbz.github.io/slides/bibcast16 and the video at https://bibcast.openbiblio.eu/lobid-organisations-ein-umfassender-index-deutscher-informationseinrichtungen/

**Comment by acka47** [comment]
Won't fix. Closing.
