### ISSUE TITLE
Remove ebook packages

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-organisations#207]
From offline discussion with @acka47: we should remove the ebook resources (during the transformation), which are no actual organisations.

See http://beta.lobid.org/organisations/search?q=*+AND+classification.label:%22Paket%20elektronischer%20Ressourcen%22&format=html

**Comment by SBRitter** [comment]
Deployed to staging: http://test.lobid.org/organisations/search?q=*

See the difference between total organisations in beta (http://beta.lobid.org/organisations/search?q=*) and staging: 23368−21842 = 1526. Equals (roughly) the number of organisations with type "Collection" in beta (1527, deviation due to updates, maybe?).

**Comment by fsteeg** [comment]
+1
