### ISSUE TITLE
Queries with large size parameters don't work

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#324]
These work:
http://lobid.org/organisations/search?q=*&size=2558&format=csv%3Aname%2Cisil%2Clocation%5B0%5D.address.addressLocality
http://lobid.org/organisations/search?q=type:Archive&size=15000&format=csv%3Aname%2Cisil%2Clocation%5B0%5D.address.addressLocality
http://lobid.org/organisations/search?q=type:Museum&size=15000&format=csv%3Aname%2Cisil%2Clocation%5B0%5D.address.addressLocality

These don't:

http://lobid.org/organisations/search?q=*&size=2559&format=csv%3Aname%2Cisil%2Clocation%5B0%5D.address.addressLocality
http://lobid.org/organisations/search?q=type:Library&size=15000&format=csv%3Aname%2Cisil%2Clocation%5B0%5D.address.addressLocality

**Comment by fsteeg** [comment]
Root cause of the problem was a wrong ISIL in the DBS data (wrong: DE-KI95, correct: DE-Ki95), resulting in two ISILs, making the value an array instead of the expected string during CSV export. When the result size got larger, it became part of the result and the issue was hit. There are two parts to fixing this:

1. Handle unexpected non-string values in CSV export (f73da032ddcf7180fbf738f448e329cfb2c9684f)
2. Update our ZIP file (http://quaoar1.hbz-nrw.de:7001/assets/data/dbs.zip) with correct ISIL

Deployed to staging:

http://stage.lobid.org/organisations/search?q=*&size=2559&format=csv%3Aname%2Cisil%2Clocation%5B0%5D.address.addressLocality

http://stage.lobid.org/organisations/DE-Ki95

**Comment by ChristophEwertowski** [comment]
+1
