### ISSUE TITLE
Wrong address for DE-1393-BOT

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#34]
Issue found via https://github.com/lobid/lodmill/issues/659.

http://beta.lobid.org/organisations/DE-1393-BOT gives the following address information:

```
address": {

    "type": "http://schema.org/PostalAddress",
    "addressCountry": "Germany",
    "postalCode": "46240",
    "streetAddress": "Tannenstr. 43",
    "addressLocality": "Bottrop"

}
```

This address doesn't occur in the [source data](http://dispatch.opac.dnb.de/DB=1.2/SET=1/TTL=1/PRS=PP%7F/NXT) at all where it reads:
```
032P	$aLützowstraße 5$bBottrop$dDE$e46236$fNordrhein-Westfalen$iMo-Fr 8.00-18.00$jabweichende Öffnungzeiten siehe Homepage$k6.92718$l51.52742$n05512000$pj$2S
032P	$aMellinghofer Str. 55$bMülheim/Ruhr$dDE$e45473$fNordrhein-Westfalen$hGebäude 35$pj$2P
```

@SBRitter: Do you have an idea what went wrong there?

**Comment by acka47** [comment]
Also, the opening hours information isn't correct in the JSON-LD. Other fields look good, though.

**Comment by philboeselager** [comment]
All three named streetAdresses refer to an office of "Hochschule Ruhr West". This indicates that there has not been a fault in mixing up different organizations but merely un unclarity.
(As I've seen, Lützowstraße 5 is a relatively new building. May that clarify things already?)

**Comment by philboeselager** [comment]
@acka47 As far as I've found out it is correct that "Mellinghofer Str. 55" is not included is not integrated in DE-1393-BOT since all data sources name that streetAddress for DE-1393 (located in Mühlheim an der Ruhr). Maybe you eventually have done a search for "DE-1393" instead of "DE-1393-BOT"? I guess we should not keep on searching got that address.

The remaining question is: why does http://dispatch.opac.dnb.de offer "Lützowstr. 55" for DE-1393-BOT whereas our dumps (still) contain the old address "Tannenstr. 43". Any ideas?

**Comment by philboeselager** [comment]
Well, there is another potential confusion. DE-1393-BOT is described on http://dispatch.opac.dnb.de by:
Haupt-/Sitzanschrift: Lützowstraße 5, 46236 Bottrop
Postanschrift: Mellinghofer Str. 55, Gebäude 35, 45473 Mülheim/Ruhr
whereas DE-1393 contains:
Haupt-/Sitzanschrift: Dümptener Str. 45, Bauteil I, 2.OG, 45476 Mülheim/Ruhr
Postanschrift: Mellinghofer Str. 55, Gebäude 35, 45473 Mülheim/Ruhr
