### ISSUE TITLE
Wrong organisations entry

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#354]
https://lobid.org/organisations/DE-197 should be the "Stadtbibliothek Leipzig", see http://ld.zdb-services.de/resource/organisations/DE-197 but it is now named "Behörde für Wirtschaft,Verkehr und Innovation/ Zentralverwaltung / Interne Dienste / Bücherei".

Obviously, this has data from the (now closed) organisation with Sigel "H 197" in there, see http://sigel.staatsbibliothek-berlin.de/suche/?isil=DE-H197. Though the data is deleted in the ISIL registry, it fetches the information from the DBS file.

This is one reason more to prefer Sigel over DBS data (see #41) as deletions are more timely there.

**Comment by fsteeg** [comment]
This is actually unrelated to the fact that the organisation is closed, but it still might have not come up if we preferred Sigel in general. The actual issue is a wrong ISIL (DE-197) for H 197 (should be DE-H197) in the DBS data. I've fixed the issue in our server data, it's deployed to staging:

 http://stage.lobid.org/organisations/DE-197

@acka47 I remember we fixed DBS data issues before. What's the process to fix it in the source data?

**Comment by acka47** [comment]
> I remember we fixed DBS data issues before. What's the process to fix it in the source data?

This is still to be defined, see #94.

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
I will talk to Ira (probably next week) regarding the workflow.

**Comment by ChristophEwertowski** [comment]
@acka47 Where does the information comes from that it should be "Behörde für Wirtschaft,Verkehr und Innovation/ Zentralverwaltung / Interne Dienste / Bücherei"? And why are both labels from the DBS ("Leipziger Städtische Bibliotheken") and in the Sigel data ("Stadtbibliothek Leipzig, Zentralbibliothek") different from that?

**Comment by acka47** [comment]
A @fsteeg writes above:

> The actual issue is a wrong ISIL (DE-197) for H 197 (should be DE-H197) in the DBS data

**Comment by ChristophEwertowski** [comment]
Sorry, it was a misunderstanding from my side. +1

**Comment by fsteeg** [comment]
Deployed to production, closing. See http://lobid.org/organisations/DE-197
