### ISSUE TITLE
Updates are broken

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-organisations#373]
As mentioned in https://github.com/hbz/lookup-tables/issues/7#issuecomment-325923414 and elsewhere the data is not up to date.

**Comment by acka47** [comment]
We should also set up some automatic tests whether the data is updated so that we are directly notified when the data is not updated anymore.

**Comment by dr0i** [comment]
As mentioned in #347 our `pelias` server was not up due to a reboot and a missing init-start-script (which I have provided now). Without that geo-service data couldn't be built.

@acka47 kind of complex to determine if data is updated. That depends on a lot of things and sometimes data isn't updated for weeks. What we *should* do so, however, is to check if the data could be build *at all*.

**Comment by acka47** [comment]
I am curious how many other ISIL resources are actually missing. We should compare a direct query against the index for the ISIL field with the number of records in the ISIL SRU export. (We need to directly query the index because eresource packags (#207) and deleted entries (#360) aren't queried using the web API.) Can you do this, @dr0i?
