### ISSUE TITLE
"address" as top level element?

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-organisations#456]
Some of the mapped sigil records seem to have an top level element `address`. Due to: https://github.com/hbz/lobid-organisations/blob/910347dc62f9bed669ac5c81a16ae0a6d035aa14/conf/morph-enriched.xml#L169-L179

```
 "address": {
    "addressLocality": "Bochum",
    "type": "PostalAddress",
    "addressCountry": "DE",
    "postalCode": "44780"
  },
```

See: http://lobid.org/organisations/DE-294.json
This is not documented [here](http://lobid.org/organisations/api/de) and seems to be redundant to the info in `location.address`.

Is this intentional?

**Comment by acka47** [comment]
> This is not documented [here](http://lobid.org/organisations/api/de) and seems to be redundant to the info in location.address.
>
> Is this intentional?

Hmm, it has been a long time... What I can say is that this is *not* redundant. In general, some entries in ISIL registry have two addresses (see https://github.com/lobid/lodmill/issues/659 & https://github.com/lobid/lodmill/issues/486). It looks like one of those is put under `location.address`, the other under `address`. See also this example: http://lobid.org/organisations/DE-11

I assume, it was an intentional decision to do it like that but can not remember or find an issue with the decision.

**Comment by TobiasNx** [comment]
closing
