### ISSUE TITLE
Report list of organisations missing geo data (Nominatim entries)

### ISSUE THREAD

**Issue by philboeselager** [hbz/lobid-organisations#77]
All entries that no geo data could be retrieved for should be listed. By doing so, notifications to the owners of the according organisations could be generated.

**Comment by fsteeg** [comment]
Added logging to the geodata lookup call, and counted failed calls with:

`cat target/universal/stage/logs/application.log | grep 'Not Found' | wc -l`

Result: 9238. Since we have two calls for each address (lat, long) this means we have failing geo lookups for 4619 DBS organisations. On staging, we have 17330 organisations with geo data [1], and 21863 total [2]. The difference is 4533. Seems to make sense.

Saved the failed calls log to `sol@quaoar1:~/git/lobid-organisations-staging/missing-geo.txt`

[1] http://test.lobid.org/organisations/search?q=location.geo:*
[2] http://test.lobid.org/organisations/search

**Comment by fsteeg** [comment]
Tweaked logging to include the passed key and updated output file.

`cat target/universal/stage/logs/application.log | grep 'Geo lookup response status not OK' | wc -l` -> `9238`

Numbers match previous run. All are 404:

` cat target/universal/stage/logs/application.log | grep '404 (Not Found)' | wc -l` -> `9238`

**Comment by fsteeg** [comment]
Tweaked controller behavior on geodata-staging: return `internal server error` status if result is null to distinguish processing errors from actual `not found` errors due to wrong paths when calling from a client.

`sol@quaoar1:~/git/lobid-organisations-staging$ cat target/universal/stage/logs/application.log | grep '404 (Not Found)' | wc -l` -> `306`
`sol@quaoar1:~/git/lobid-organisations-staging$ cat target/universal/stage/logs/application.log | grep '500 (Internal Server Error)' | wc -l` -> `8932`

Meaning 153 requests fail due to wrong lookup paths created during the transformation in lobid-organisations, and 4466 due to internal geodata issues (processing errors or no results from services).

**Comment by fsteeg** [comment]
Tickets for solving the underlying issues: https://github.com/hbz/lobid-organisations/issues/251 for lobid-organisations, https://github.com/hbz/lobid-organisations/issues/89 for geodata. Closing this.
